import { parseYuan, splitTags } from '../lib/submission-limits';
import { useEffect, useState } from 'react';
import { notifyForm } from '../utils/form-feedback';
import { safePublicImage, tagLabel } from '../utils/catalog-display';
import '../styles/admin-workspace.css';
type Data = Record<string, any>;
type Entry = { type: 'food'|'venue'|'review'; record: Data; hash: string };
const statuses:Record<string,string>={pending:'待审核',queued:'等待生成发布申请',running:'正在生成发布申请',pr_open:'等待合并',merged_dev:'预览已更新',merged_main:'等待正式部署',deployed:'已正式发布',failed:'发布失败',closed:'申请已关闭',export_failed:'发布失败',exporting:'准备发布'};
const types:Record<string,string>={food:'餐品',venue:'店铺',review:'评价',management:'内容修改'};
async function api(path:string,init:RequestInit={}){const response=await fetch('/api/v2/admin'+path,{...init,cache:'no-store',headers:{'Content-Type':'application/json',...init.headers}});const data=await response.json().catch(()=>null);if(!response.ok||!data)throw new Error(data?.error?.message||'审核会话可能已到期，请重新登录或刷新。');return data;}
function PrivatePhoto({id,asset,compact=false}:{id:string;asset:Data;compact?:boolean}){const [url,setUrl]=useState('');useEffect(()=>{let object='';const controller=new AbortController();fetch(`/api/v2/admin/submissions/${id}/images/${asset.id}`,{cache:'no-store',signal:controller.signal}).then(async response=>{if(!response.ok)return;const blob=await response.blob();if(!controller.signal.aborted){object=URL.createObjectURL(blob);setUrl(object);}}).catch(()=>{});return()=>{controller.abort();if(object)URL.revokeObjectURL(object);};},[id,asset.id]);if(compact)return url?<img src={url} alt={asset.alt||'投稿照片'}/>:<span className="admin-type-icon">图</span>;return <figure>{url?<a href={url} target="_blank" rel="noreferrer"><img src={url} alt={asset.alt}/></a>:<div className="photo-placeholder">照片暂未加载</div>}<figcaption>{asset.alt}<small>{asset.slot==='attachedReview'?'随稿评价':'投稿照片'} · {asset.copyright_holder} · {asset.license}{asset.is_illustrative?' · 示意图':''}</small></figcaption></figure>;}
function Field({label,value,onChange,multiline=false,required=false,type='text',max=2000}:{label:string;value:any;onChange:(v:string)=>void;multiline?:boolean;required?:boolean;type?:string;max?:number}){return <label className="admin-field"><span>{label}{required&&<b className="required-mark"> *</b>}</span>{multiline?<textarea value={value??''} maxLength={max} rows={4} onChange={e=>onChange(e.target.value)}/>:<input type={type} required={required} value={value??''} maxLength={max} min={type==='number'?0:undefined} step={type==='number'?'0.01':undefined} onChange={e=>onChange(e.target.value)}/>}</label>;}
function PriceEditor({price,venue,canonical,change}:{price:Data|null;venue:boolean;canonical:boolean;change:(v:Data|null)=>void}) {
 const [range,setRange]=useState(Boolean(price&&price.amountCents==null&&price.minCents!==price.maxCents));
 const base=()=>({currency:'CNY',unit:venue?'人':'份',source:price?.source??'',verifiedAt:price?.verifiedAt??null});
 const update=(field:string,value:string)=>{
  const cents=value===''?null:parseYuan(value)??NaN;
  if(range){change({...base(),minCents:price?.minCents??null,maxCents:price?.maxCents??null,[field]:cents});}
  else change(value===''?null:{...base(),...(venue&&canonical?{minCents:cents,maxCents:cents}:{amountCents:cents})});
 };
 return <fieldset className="admin-meals"><legend>{venue?'人均消费':'餐品价格'}（元）</legend><label><input type="checkbox" checked={range} onChange={e=>{setRange(e.target.checked);const amount=price?.amountCents??price?.minCents??null;change(price?{...base(),...(e.target.checked||venue&&canonical?{minCents:amount,maxCents:price?.maxCents??amount}:{amountCents:amount})}:null);}}/>不确定 / 价格有浮动</label>
 {range?<><Field label="最低价" type="number" value={price?.minCents==null?'':price.minCents/100} onChange={v=>update('minCents',v)}/><Field label="最高价" type="number" value={price?.maxCents==null?'':price.maxCents/100} onChange={v=>update('maxCents',v)}/><button type="button" onClick={()=>change(null)}>价格未知，清空区间</button></>:<Field label="金额" type="number" value={price?(price.amountCents??price.minCents??0)/100:''} onChange={v=>update('amountCents',v)}/>}
 <small>未知可留空；区间两端都要填写，最高价不能低于最低价。</small></fieldset>;
}
function EntityFields({type,value,change,venues,canonical}:{type:string;value:Data;change:(v:Data)=>void;venues:Entry[];canonical:boolean}){
 const put=(key:string,v:any)=>change({...value,[key]:v});
 const select=(label:string,key:string,options:string[][])=><label className="admin-field">{label}<select disabled={key==='venueId'&&!canonical} value={value[key]??''} onChange={e=>put(key,e.target.value||null)}>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>;
 const pk=type==='venue'?'averagePrice':'price',price=value[pk];
 return <div className="admin-form-grid"><Field label="名称" value={value.name} required max={120} onChange={v=>put('name',v)}/>
 {type==='food'?<>{select('所属店铺','venueId',[...venues.filter(e=>e.record.status!=='archived').map(e=>[e.record.id,e.record.name]),...(!venues.some(e=>e.record.id===value.venueId)&&value.venueId?[[value.venueId,'待发布的所属店铺']]:[])])}<fieldset className="admin-meals"><legend>餐段</legend>{[['breakfast','早餐'],['meal','正餐'],['snack','小吃'],['dessert','甜点'],['drink','饮品']].map(([id,label])=>{const meals=value.mealTypes??(value.mealType?[value.mealType]:[]);return <label key={id}><input type="checkbox" checked={meals.includes(id)} onChange={e=>{const next:Data={...value,mealTypes:e.target.checked?[...meals,id]:meals.filter((v:string)=>v!==id)};delete next.mealType;change(next);}}/>{label}</label>;})}</fieldset></>:<>
 {select('店铺类型',canonical?'kind':('kind' in value?'kind':'type'),[['cafeteria','食堂'],['stall','档口'],['restaurant','餐厅'],['cafe','咖啡 / 饮品'],['convenience','便利店']])}
 {select('范围',canonical?'category':('category' in value?'category':'campusScope'),[['on-campus','校内'],['off-campus','校外']])}
 {canonical&&select('所属食堂 / 上级店铺','parentId',[['','无上级店铺'],...venues.filter(e=>e.record.id!==value.id&&e.record.status!=='archived').map(e=>[e.record.id,e.record.name])])}
 {['address','campusArea','floor','landmark'].map((key,i)=><Field key={key} label={['位置 / 地址','校区 / 区域','楼层','附近地标'][i]} required={i===0} value={value.location?.[key]} max={i===0?300:100} onChange={v=>put('location',{...value.location,[key]:v||null})}/>)}
 <Field label="校外距离（米）" type="number" value={value.location?.distanceMeters} onChange={v=>put('location',{...value.location,distanceMeters:v===''?null:Number(v)})}/><label className="admin-field">距离依据<select value={value.location?.distanceBasis??''} onChange={e=>put('location',{...value.location,distanceBasis:e.target.value||null})}><option value="">未知</option><option value="walking">步行</option><option value="straight-line">直线距离</option><option value="reported">投稿者提供</option></select></label><Field label="营业时间" value={value.openingHours} max={300} onChange={v=>put('openingHours',v||null)}/></>}
 <label className="admin-field">中文标签（空格分隔）<input key={value.id??value.name} defaultValue={(value.tags??[]).map(tagLabel).join(' ')} maxLength={1800} onBlur={e=>put('tags',splitTags(e.target.value))}/></label>
 <PriceEditor key={(value.id??value.name)+type} price={price??null} venue={type==='venue'} canonical={canonical} change={v=>put(pk,v)}/>
 {price&&<><Field label="价格来源" required max={300} value={price.source} onChange={v=>put(pk,{...price,source:v})}/>{type==='food'&&<Field label="计价单位" required max={20} value={price.unit} onChange={v=>put(pk,{...price,unit:v})}/>}</>}
 <div className="admin-full"><Field label="介绍" value={value.description} multiline max={type==='food'?1000:2000} onChange={v=>put('description',v||null)}/></div></div>;
}
function ReviewFields({value,change}:{value:Data;change:(v:Data)=>void}){return <div className="admin-attached"><label className="admin-field">星级<select value={value.rating??''} onChange={e=>change({...value,rating:Number(e.target.value)})}><option value="">请选择评分</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} 星</option>)}</select></label><Field label="评价文字" multiline value={value.text} max={512} onChange={v=>change({...value,text:v})}/><small>{Array.from(value.text??'').length} / 256 字</small></div>;}

export default function AdminWorkspace(){
 const [mode,setMode]=useState(''),[backup,setBackup]=useState<Data|null>(null);
 const [tab,setTab]=useState('queue'),[entries,setEntries]=useState<Entry[]>([]),[queue,setQueue]=useState<Data[]>([]),[jobs,setJobs]=useState<Data[]>([]),[active,setActive]=useState<Data[]>([]);
 const [query,setQuery]=useState(''),[type,setType]=useState('all'),[status,setStatus]=useState('all'),[cards,setCards]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [selected,setSelected]=useState<Entry|null>(null),[detail,setDetail]=useState<Data|null>(null),[draft,setDraft]=useState<Data|null>(null),[reason,setReason]=useState(''),[cursor,setCursor]=useState<string|null>(null);
 async function cleanupLegacy(){
  if(!window.confirm('下架旧资料迁入的餐品及关联评价，保留真实投稿和店铺；转换中文标签。所有下架均可恢复。继续？'))return;
  setBusy(true);setError('');
  try{let result;do{result=await api('/maintenance/legacy-catalog',{method:'POST',headers:{'Content-Type':'application/json','X-Catalog-Maintenance':'archive-legacy-and-localize-tags'}});}while(result.remaining>0);notifyForm('旧资料已下架，中文标签已保留。','success');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 async function refresh(){setLoading(true);setError('');try{const [c,q,p]=await Promise.all([api('/content'),api('/submissions?status=pending'),api('/publications')]);setEntries(c.entries);setActive(c.active);setQueue(q.submissions);setCursor(q.nextCursor);setJobs(p.publications);setMode(p.mode??'legacy');setBackup(p.backup??null);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void refresh();},[]);
 function close(){setSelected(null);setDetail(null);setDraft(null);setReason('');}
 function switchTab(next:string){setTab(next);close();setQuery('');setType('all');setStatus('all');}
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);try{await action();}catch(e){notifyForm((e as Error).message,'error');}finally{setBusy(false);}}
 function openEntry(entry:Entry){setDetail(null);setSelected(entry);setDraft(structuredClone(entry.record));setReason('');}
 async function openSubmission(id:string){await run(async()=>{const data=await api('/submissions/'+id);setSelected(null);setDetail(data);setDraft(JSON.parse(data.submission.revision_json).payload);setReason('');});}
 async function savePending(){if(!detail||!draft)return;const revision={...JSON.parse(detail.submission.revision_json),payload:draft};const result=await api('/submissions/'+detail.submission.id,{method:'PATCH',body:JSON.stringify({expectedVersion:detail.submission.version,revision})});const next={...detail,submission:{...detail.submission,version:result.version,revision_json:JSON.stringify(result.revision)}};setDetail(next);return next;}
 async function review(action:'approve'|'reject'){await run(async()=>{if(!detail)return;if(action==='reject'&&!reason.trim())throw new Error('请填写拒绝原因。');const saved=action==='approve'?await savePending():detail;if(!saved)return;await api('/submissions/'+saved.submission.id+'/review',{method:'POST',body:JSON.stringify({action,expectedVersion:saved.submission.version,reason})});notifyForm(action==='approve'?(mode==='live'?'审核通过，已立即公开。GitHub 将异步备份。':'审核通过，已进入发布队列；部署完成后公开。'):'已拒绝投稿并保存原因。','success');close();await refresh();});}
 const venues=entries.filter(e=>e.type==='venue');
 const shown=entries.filter(e=>(type==='all'||e.type===type)&&(status==='all'||(e.record.status??'published')===status)&&[e.record.name,e.record.text,e.record.location?.address].filter(Boolean).join(' ').toLowerCase().includes(query.toLowerCase()));
 const pending=queue.filter(e=>(type==='all'||e.entity_type===type)&&[e.name,e.review_text,e.entity_id].filter(Boolean).join(' ').toLowerCase().includes(query.toLowerCase()));
 const locked=selected&&active.some(e=>e.entity_id===selected.type+':'+selected.record.id);
 const candidates:Data[]=selected&&draft&&selected.type!=='review'?[...draft.images.map((image:Data)=>({image,reviewId:null})),...entries.filter(e=>e.type==='review'&&e.record.status!=='archived'&&e.record.targetType===selected.type&&e.record.targetId===draft.id).flatMap(e=>e.record.images.map((image:Data)=>({image,reviewId:e.record.id})))]:[];
 const cover=candidates.find(c=>c.image.url===draft?.cover?.url&&c.reviewId===draft?.cover?.reviewId)?.image;
 return <main className="admin-page"><header className="admin-title"><div><p>CONTENT WORKSPACE</p><h1>把每一份推荐，照顾好。</h1><span>审核投稿、维护资料与照片。审核通过或保存修改后立即公开，历史版本可追溯。</span></div><button disabled={loading||busy} onClick={()=>void refresh()}>↻ 刷新</button></header>
 <nav className="admin-tabs" aria-label="管理功能">{[['queue','待审核',queue.length],['content','内容管理',entries.length],['media','图片管理',entries.reduce((n,e)=>n+e.record.images.length,0)],['publications','发布记录',jobs.filter(j=>j.status!=='deployed').length]].map(([id,label,n])=><button key={id} aria-pressed={tab===id} disabled={busy} onClick={()=>switchTab(String(id))}>{label}<span>{n}</span></button>)}</nav>
 {error&&<p role="alert" className="admin-error">{error} <a href="/admin/">重新登录 →</a></p>}
 {loading?<p className="admin-empty">正在加载管理工作区…</p>:tab==='publications'?<section className="admin-jobs"><h2>公开与备份</h2><p>审核通过后直接写入 Cloudflare 并公开，GitHub 备份不影响线上可见性。</p>{backup&&<article><div><strong>GitHub 异步备份</strong><small>线上版本 {backup.revision} · 已备份版本 {backup.backed_revision}</small></div><span className="admin-status">{backup.backed_revision>=backup.revision?'已同步':'待同步（每 30 分钟尝试）'}</span><a href="https://github.com/Conduit-Club/SHOU-What-To-Eat/actions/workflows/backup-catalog.yml" target="_blank" rel="noreferrer">查看 / 手动运行备份 ↗</a></article>}{jobs.length?jobs.map(job=><article key={job.id}><div><strong>{job.name||types[job.entity_type]||'投稿'}</strong><small>{new Date(job.updated_at).toLocaleString('zh-CN')} · {job.id.slice(0,8)}</small></div><span className={'admin-status '+(job.status==='deployed'?'good':'')}>{job.submission_status==='rejected'?'已取消修改':(job.status==='legacy_pending'?'旧稿接续处理中':statuses[job.status]||job.status)}</span>{job.error_code&&<span className="admin-error">{job.error_code==='catalog_revision_conflict'?'版本冲突：请取消修改并刷新后重新编辑。':job.error_code}</span>}{job.pr_url&&/^https:\/\/github\.com\//.test(job.pr_url)&&<a href={job.pr_url} target="_blank" rel="noreferrer">查看发布申请 ↗</a>}{job.submission_status!=='rejected'&&['failed','closed'].includes(job.status)&&<><button disabled={busy} onClick={()=>void run(async()=>{await api('/publications/'+job.id+'/retry',{method:'POST'});await refresh();notifyForm('已重新加入发布队列。','success');})}>重试</button>{job.entity_type==='management'&&<button disabled={busy} onClick={()=>void run(async()=>{await api('/content-changes/'+job.id+'/cancel',{method:'POST'});await refresh();notifyForm('已取消失败修改，可以重新编辑。','success');})}>取消修改</button>}</>}</article>):<p className="admin-empty">还没有发布记录。</p>}</section>:<>
 <div className="admin-toolbar"><input type="search" aria-label="搜索管理内容" placeholder="按名称、位置或评价文字找…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="内容类型" value={type} onChange={e=>setType(e.target.value)}><option value="all">全部类型</option><option value="food">餐品</option><option value="venue">店铺</option><option value="review">评价</option></select>{tab!=='queue'&&<><select aria-label="上下架状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">所有状态</option><option value="published">已上架</option><option value="archived">已下架</option></select><button aria-pressed={cards} onClick={()=>setCards(!cards)}>{cards?'切换列表':'切换卡片'}</button><a href="/submit/">＋ 新增餐品 / 店铺</a></>}</div>
 <div className={'admin-workspace '+(selected||detail?'has-selection':'')}><section className={'admin-items '+(cards?'cards':'')} aria-label="内容列表">
 {tab==='queue'?pending.map(item=><button className={'admin-row '+(detail?.submission.id===item.id?'selected':'')} key={item.id} disabled={busy} onClick={()=>void openSubmission(item.id)}><>{item.thumbnail_id?<PrivatePhoto id={item.id} asset={{id:item.thumbnail_id,alt:item.name||'投稿照片'}} compact/>:<span className="admin-type-icon">{types[item.entity_type]?.slice(0,1)}</span>}</><span><strong>{item.name||item.review_text?.slice(0,40)||'新的'+types[item.entity_type]}</strong><small>{types[item.entity_type]} · {new Date(item.created_at).toLocaleDateString('zh-CN')} · {item.expected_images+item.expected_review_images} 张照片</small></span><span className="admin-status">{item.upload_state==='pending'?'待审核':'上传未完成'}</span></button>):shown.filter(e=>tab!=='media'||e.record.images.length||e.type!=='review'&&entries.some(r=>r.type==='review'&&r.record.targetType===e.type&&r.record.targetId===e.record.id&&r.record.images.length)).map(entry=>{const photo=entry.record.images.map(safePublicImage).find(Boolean);return <button className={'admin-row '+(selected===entry?'selected':'')} key={entry.type+entry.record.id} disabled={busy} onClick={()=>openEntry(entry)}>{photo?<img src={photo.url} alt={photo.alt} loading="lazy"/>:<span className="admin-type-icon">{types[entry.type]?.slice(0,1)}</span>}<span><strong>{entry.record.name||entry.record.text||'仅评分评价'}</strong><small>{types[entry.type]} · {entry.record.images.length} 张照片</small></span><span className="admin-status">{entry.record.status==='archived'?'已下架':'已上架'}</span></button>;})}
 {tab==='queue'&&!pending.length&&<div className="admin-empty"><span>✓</span><h2>暂时没有待审核投稿</h2><p>新投稿完成图片上传后，会出现在这里。</p><button onClick={()=>switchTab('content')}>去维护已有内容 →</button></div>}{tab!=='queue'&&!shown.length&&<p className="admin-empty">没有匹配内容，试着调整筛选。</p>}{tab==='queue'&&cursor&&<button onClick={()=>void run(async()=>{const data=await api('/submissions?status=pending&cursor='+encodeURIComponent(cursor));setQueue([...queue,...data.submissions]);setCursor(data.nextCursor);})}>加载更多</button>}
 </section>
 {(selected||detail)&&draft&&<section className="admin-editor" aria-label="内容编辑"><header><div><p>{selected?'维护已收录内容':'审核投稿'}</p><h2>{draft.name||'同学评价'}</h2></div><button disabled={busy} onClick={close}>关闭</button></header>{locked&&<p className="admin-warning">已有待发布修改，请先在发布记录中完成或取消该修改。</p>}
 <form onSubmit={e=>{e.preventDefault();void run(async()=>{if(selected){await api('/content/'+selected.type+'/'+selected.record.id,{method:'POST',body:JSON.stringify({expectedHash:selected.hash,record:draft,reason})});notifyForm(mode==='live'?'修改已公开，GitHub 备份待同步。':'修改已保存并进入发布队列；部署成功后线上生效。','success');close();await refresh();}else{await savePending();notifyForm('审核稿已保存，尚未批准发布。','success');}});}}><fieldset disabled={busy||Boolean(locked)}>
 {(selected?.type??detail?.submission.entity_type)==='review'?(selected?<><p>{draft.text||'没有文字评价'}</p><p>★ {draft.rating??'未评分'} · {draft.authorAlias||'匿名同学'}</p><small>保留评价原意；可下架评价或隐藏照片。</small></>:<ReviewFields value={draft} change={setDraft}/>):<EntityFields type={selected?.type??detail?.submission.entity_type} value={draft} change={setDraft} venues={venues} canonical={Boolean(selected)}/>}
 {!selected&&draft.attachedReview&&<details open className="admin-attached"><summary>随稿评价 · 一并审核</summary><ReviewFields value={draft.attachedReview} change={review=>setDraft({...draft,attachedReview:review})}/></details>}
 {detail&&<><h3>投稿照片与来源</h3><div className="admin-photo-grid">{detail.media.map((asset:Data)=><PrivatePhoto key={asset.id} id={detail.submission.id} asset={asset}/>)}</div>{!detail.media.length&&<p>这条投稿没有照片。</p>}</>}
 {selected&&<><h3>公开状态</h3><label className="admin-field">下架后退出公开目录，历史内容保留<select value={draft.status??'published'} onChange={e=>setDraft({...draft,status:e.target.value})}><option value="published">上架</option><option value="archived">下架（可恢复）</option></select></label>
 {selected.type!=='review'&&<><h3>封面照片</h3><p className="admin-help">可选对应内容已审核、获授权的实拍图。评价原图、作者和来源保持不变。</p>{cover&&<div className="admin-cover-preview"><img src={cover.url} alt={cover.alt} style={{objectPosition:`${draft.cover.x}% ${draft.cover.y}%`}}/></div>}{draft.cover&&<div className="admin-form-grid">{['x','y'].map((axis,i)=><label className="admin-field" key={axis}>{i?'上下裁切焦点':'左右裁切焦点'}<input type="range" min="0" max="100" value={draft.cover[axis]} onChange={e=>setDraft({...draft,cover:{...draft.cover,[axis]:Number(e.target.value)}})}/></label>)}</div>}<button type="button" onClick={()=>setDraft({...draft,cover:null})}>恢复默认封面</button><div className="admin-photo-grid">{candidates.map(({image,reviewId})=>{const eligible=image.permission==='approved'&&!image.hidden&&!image.isIllustrative&&(!reviewId||image.coverEligible);return <figure key={String(reviewId)+image.url}>{safePublicImage({...image,url:image.url,hidden:false})&&<img src={image.url} alt={image.alt} loading="lazy"/>}<figcaption>{image.alt}<small>{reviewId?'来自评价':'投稿原图'} · {image.author||'匿名同学'} · {image.license}</small></figcaption><button type="button" disabled={!eligible} onClick={()=>setDraft({...draft,cover:{url:image.url,reviewId,x:50,y:50}})}>{draft.cover?.url===image.url&&draft.cover?.reviewId===reviewId?'当前封面':eligible?'选作封面':image.hidden?'已隐藏':image.isIllustrative?'示意图不能精选':'缺少封面授权'}</button>{reviewId?<button type="button" onClick={()=>openEntry(entries.find(e=>e.type==='review'&&e.record.id===reviewId)!)}>管理原评价照片 →</button>:<button type="button" onClick={()=>setDraft({...draft,cover:draft.cover?.url===image.url?null:draft.cover,images:draft.images.map((original:Data)=>original.url===image.url?{...original,hidden:!original.hidden}:original)})}>{image.hidden?'恢复显示':'隐藏此图'}</button>}</figure>;})}</div>{!candidates.length&&<p className="admin-help">还没有可选照片。<a href={(selected.type==='food'?'/foods/':'/restaurants/')+draft.id+'/#review-form'}>通过评价补充照片 →</a></p>}</>}
 {selected.type==='review'&&<div className="admin-photo-grid">{draft.images.map((image:Data,index:number)=><figure key={image.url}>{safePublicImage({...image,url:image.url,hidden:false})&&<img src={image.url} alt={image.alt}/>}<figcaption>{image.alt}<small>{image.author} · {image.license}</small></figcaption><button type="button" onClick={()=>setDraft({...draft,images:draft.images.map((original:Data,i:number)=>i===index?{...original,hidden:!original.hidden}:original)})}>{image.hidden?'恢复显示':'隐藏照片'}</button></figure>)}</div>}</>}
 <Field label={selected?'修改原因（保存在私有审核历史）':'拒绝原因（拒绝时必填）'} required={Boolean(selected)} max={500} value={reason} onChange={setReason}/><div className="admin-actions"><button type="submit" className="primary">{selected?(mode==='live'?'保存并立即公开':'保存修改并申请发布'):'保存审核稿'}</button>{!selected&&<><button type="button" className="primary" disabled={detail?.submission.upload_state!=='pending'} onClick={()=>void review('approve')}>{mode==='live'?'批准并立即公开':'批准并申请发布'}</button><button type="button" className="danger" onClick={()=>void review('reject')}>拒绝投稿</button></>}</div>
 </fieldset></form>{detail&&<details className="admin-audit"><summary>审核历史（{detail.audits.length}）</summary>{detail.audits.map((audit:Data,i:number)=><p key={i}>{audit.created_at} · {audit.reviewer} · {audit.action} {audit.reason}</p>)}</details>}</section>}
 </div></>}
 {mode==='live'&&<details className="admin-audit"><summary>历史资料整理</summary><p>下架旧资料迁入的餐品和关联评价，保留店铺、真实投稿、原文与来源；将已有标签转换为中文。</p><button type="button" disabled={busy} onClick={()=>void cleanupLegacy()}>{busy?'正在整理…':'整理旧资料（下架可恢复）'}</button></details>}
 </main>;
}
