import { useEffect,useMemo,useState } from 'react';
import CatalogCards from './CatalogCards';
import { useCatalog } from './useCatalog';
import { matchesDiscoveryFood,type FoodFilters } from '../utils/food-discovery';
import { foodCard,venueCard,matchesDiscoveryVenue,type CatalogCard,type DiscoveryCatalog } from '../utils/catalog-discovery';
import { tagLabel } from '../utils/catalog-display';
const emptyCatalog:DiscoveryCatalog={foods:[],venues:[]};
const scopes=['all','on-campus','off-campus','within-500','within-1000','within-2000'];
export default function CatalogSearch() {
  const {catalog,loading,error,retry}=useCatalog(emptyCatalog);
  const [ready,setReady]=useState(false);
  const [draft,setDraft]=useState('');const [query,setQuery]=useState('');const [type,setType]=useState('all');
  const [scope,setScope]=useState('all');const [meal,setMeal]=useState('all');const [budget,setBudget]=useState('all');const [tag,setTag]=useState('all');const [sort,setSort]=useState('name');
  useEffect(()=>{const params=new URLSearchParams(location.search);const q=(params.get('q')??'').slice(0,120);setDraft(q);setQuery(q);const selected=params.get('type')??'all';if(['all','food','venue','stall'].includes(selected))setType(selected);const selectedScope=params.get('scope')??'all';if(scopes.includes(selectedScope))setScope(selectedScope);const selectedSort=params.get('sort')??'name';if(['name','rating','newest'].includes(selectedSort))setSort(selectedSort);const selectedMeal=params.get('meal')??'all';if(['all','breakfast','meal','snack','dessert','drink'].includes(selectedMeal))setMeal(selectedMeal);const selectedBudget=params.get('budget')??'all';if(['all','under15','15to25','over25'].includes(selectedBudget))setBudget(selectedBudget);setTag(params.get('tag')??'all');setReady(true);},[]);
  useEffect(()=>{if(!ready)return;const params=new URLSearchParams();if(query)params.set('q',query);for(const [key,value] of Object.entries({type,scope,meal,budget,tag,sort}))if(value!=='all'&&!(key==='sort'&&value==='name'))params.set(key,value);history.replaceState(null,'','/search/'+(params.size?'?'+params.toString():''));},[ready,query,type,scope,meal,budget,tag,sort]);
  const tags=useMemo(()=>[...new Set([...catalog.foods,...catalog.venues].flatMap(item=>item.tags))].sort((a,b)=>tagLabel(a).localeCompare(tagLabel(b),'zh-CN')),[catalog]);
  const filters:FoodFilters={query,scope,meal,budget,tags:tag==='all'?[]:[tag]};
  const items:CatalogCard[]=[];
  if(type==='all'||type==='food')items.push(...catalog.foods.filter(food=>matchesDiscoveryFood(food,filters)).map(foodCard));
  if(type!=='food')items.push(...catalog.venues.filter(venue=>(type!=='stall'||venue.kind==='stall')&&matchesDiscoveryVenue(venue,catalog.foods,filters)).map(venueCard));
  items.sort((a,b)=>sort==='rating'?((b.rating??-1)-(a.rating??-1)||b.reviewCount-a.reviewCount||a.name.localeCompare(b.name,'zh-CN')):sort==='newest'?((b.addedAt??'').localeCompare(a.addedAt??'')||a.name.localeCompare(b.name,'zh-CN')):a.name.localeCompare(b.name,'zh-CN'));
  const reset=()=>{setDraft('');setQuery('');setType('all');setScope('all');setMeal('all');setBudget('all');setTag('all');setSort('name');};
  return <div className="catalog-search">
    <form className="search-bar" onSubmit={event=>{event.preventDefault();setQuery(draft.trim());}}><span aria-hidden="true">⌕</span><input aria-label="搜索餐品、餐厅或档口" type="search" placeholder="餐品、餐厅、档口、地址或标签" value={draft} maxLength={120} onChange={event=>setDraft(event.target.value)}/><button type="submit">搜索 →</button></form>
    <div className="search-type-tabs" role="group" aria-label="搜索对象">{[['all','全部结果'],['food','餐品'],['venue','全部店铺'],['stall','档口']].map(([value,label])=><button key={value} type="button" aria-pressed={type===value} onClick={()=>setType(value)}>{label}</button>)}</div>
    <details className="search-filters" open><summary>筛选条件 <span>范围 · 预算 · 餐段 · 标签</span></summary><div className="search-filter-grid">
      <label>范围<select value={scope} onChange={event=>setScope(event.target.value)}>{[['all','不限范围'],['on-campus','校内'],['off-campus','校外'],['within-500','校外 ≤500m'],['within-1000','校外 ≤1km'],['within-2000','校外 ≤2km']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
      <label>预算<select value={budget} onChange={event=>setBudget(event.target.value)}><option value="all">不限预算</option><option value="under15">15 元以下</option><option value="15to25">15–25 元</option><option value="over25">25 元以上</option></select></label>
      <label>餐段<select value={meal} onChange={event=>setMeal(event.target.value)}>{[['all','不限餐段'],['breakfast','早餐'],['meal','正餐'],['snack','小吃'],['dessert','甜点'],['drink','饮品']].map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>
      <label>标签<select value={tag} onChange={event=>setTag(event.target.value)}><option value="all">不限标签</option>{tags.map(value=><option key={value} value={value}>{tagLabel(value)}</option>)}</select></label>
    </div><p>店铺结果按人均消费或其餐品匹配预算；未知价格、距离不会参与对应筛选。</p></details>
    <header className="search-results-heading"><h2 aria-live="polite">{loading||!ready?'正在加载食单…':query?'“'+query+'” · '+items.length+' 个结果':items.length+' 个结果'}</h2><div><label>排序<select aria-label="搜索结果排序" value={sort} onChange={event=>setSort(event.target.value)}><option value="name">名称</option><option value="rating">评分优先</option><option value="newest">最近收录优先</option></select></label><button type="button" onClick={reset}>清除筛选</button></div></header>
    {error?<p className="catalog-load-error">目录加载失败，暂时无法搜索。 <button onClick={retry}>重新加载</button></p>:!loading&&ready&&(items.length?<CatalogCards items={items} progressive resetKey={JSON.stringify([query,type,scope,meal,budget,tag,sort])}/>:<div className="search-empty"><h3>没有找到符合条件的内容</h3><p>试着少选几个条件，或者换一个关键词。</p><button onClick={reset}>清除筛选，再找找</button></div>)}
    <style>{`.catalog-search{padding:0 0 40px}.search-bar{display:flex;align-items:center;gap:16px;padding:10px 12px 10px 24px;border:1px solid #e6c6ad;border-radius:22px;background:white;box-shadow:0 8px 25px -15px #d5aa8b}.search-bar>span{font-size:30px;color:#a47959}.search-bar input{flex:1;min-width:0;border:0;outline:0;background:transparent;font-size:16px;min-height:48px}.search-bar:focus-within{outline:3px solid var(--focus);outline-offset:3px}.search-bar>button{min-height:48px;padding:0 25px;border:0;border-radius:15px;background:var(--orange);color:white;font-size:14px;font-weight:750}.search-type-tabs{display:flex;gap:14px;flex-wrap:wrap;margin:26px 0 19px}.search-type-tabs>button{padding:0 17px;border:1px solid var(--line);border-radius:999px;background:white;font-size:12px;color:var(--muted)}.search-type-tabs>button[aria-pressed=true]{background:var(--ink);border-color:var(--ink);color:white}.search-filters{padding:20px 24px;border:1px solid var(--line);border-radius:21px;background:#fffdf9}.search-filters summary{font-size:13px;font-weight:750;cursor:pointer;min-height:44px}.search-filters summary>span{margin-left:15px;font-size:10px;color:var(--muted);font-weight:400}.search-filter-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:17px}.search-filter-grid label{display:grid;gap:9px;font-size:11px;color:var(--muted)}.search-filter-grid select,.search-results-heading select{min-width:0;min-height:46px;padding:0 14px;border:1px solid var(--line);border-radius:12px;background:white;color:var(--ink);font-size:13px}.search-filters>p{margin:15px 0 0;color:var(--muted);font-size:10px;line-height:1.8}.search-results-heading{display:flex;justify-content:space-between;align-items:center;gap:24px;margin:28px 0 22px}.search-results-heading h2{font-size:22px;margin:0;letter-spacing:-.025em}.search-results-heading>div{display:flex;align-items:center;gap:15px;flex:none}.search-results-heading label{display:flex;align-items:center;gap:9px;font-size:11px;color:var(--muted)}.search-results-heading button,.search-empty button{border:0;background:transparent;color:var(--orange-deep);font-size:11px;text-decoration:underline}.search-empty{padding:40px 25px;text-align:center;border:1px dashed var(--line);border-radius:22px}.search-empty h3{font-size:22px}.search-empty p{color:var(--muted);font-size:13px}@media(max-width:760px){.search-filter-grid{grid-template-columns:1fr 1fr;gap:14px}.search-filter-grid select,.search-results-heading select{font-size:16px}.search-results-heading{align-items:start;flex-direction:column;gap:13px}.search-results-heading>div{width:100%;justify-content:space-between}.search-bar{gap:10px;padding:8px 8px 8px 15px;border-radius:17px}.search-bar>button{padding:0 13px;font-size:12px}.search-bar>span{font-size:24px}.search-type-tabs{gap:8px}.search-type-tabs>button{padding:0 12px;font-size:11px}.search-filters{padding:16px}.search-filters summary>span{font-size:9px;margin-left:10px}}`}</style>
  </div>;
}
